# Generated by Django 3.1.7 on 2021-04-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stair', models.CharField(max_length=200)),
                ('karkas', models.CharField(max_length=200)),
                ('material', models.CharField(max_length=200)),
                ('rail', models.CharField(max_length=200)),
                ('rail_material', models.CharField(max_length=200)),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('long', models.IntegerField()),
                ('height_step', models.IntegerField()),
                ('obrobka', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
