# Generated by Django 3.1.7 on 2021-05-03 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accclients', '0004_auto_20210421_0937'),
        ('accsuppliers', '0002_supplier_archive'),
        ('conorders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSupplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=200)),
                ('order_date', models.DateField(null=True)),
                ('price', models.IntegerField()),
                ('complete_date', models.DateField(null=True)),
                ('phone', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('mark', models.CharField(max_length=200, null=True)),
                ('archive', models.BooleanField(default=False)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accsuppliers.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='OrderClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numlayers', models.IntegerField()),
                ('stair', models.CharField(max_length=200)),
                ('karkas', models.CharField(max_length=200)),
                ('material', models.CharField(max_length=200)),
                ('rail', models.CharField(max_length=200)),
                ('rail_material', models.CharField(max_length=200)),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('long', models.IntegerField()),
                ('height_step', models.IntegerField()),
                ('obrobka', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('order_number', models.CharField(max_length=200)),
                ('order_date', models.DateField(null=True)),
                ('approval_date', models.DateField(null=True)),
                ('address', models.CharField(max_length=200)),
                ('departure_date', models.DateField(null=True)),
                ('estimated_price', models.IntegerField()),
                ('final_price', models.IntegerField(null=True)),
                ('install_date', models.DateField(null=True)),
                ('num_days', models.IntegerField(null=True)),
                ('complete_date', models.DateField(null=True)),
                ('status', models.CharField(max_length=200)),
                ('archive', models.BooleanField(default=False)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accclients.client')),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conorders.orderclientdetails')),
            ],
        ),
    ]
