# Generated by Django 3.1.7 on 2021-05-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderclient',
            name='estimated_price',
            field=models.IntegerField(null=True),
        ),
    ]
