# Generated by Django 3.1.7 on 2021-05-03 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210503_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderclient',
            name='details',
        ),
    ]
