# Generated by Django 3.2.7 on 2021-12-25 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_statusorderclient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.statusorderclient'),
        ),
    ]
