# Generated by Django 3.1.7 on 2021-05-03 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accclients', '0004_auto_20210421_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderClientDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numlayers', models.IntegerField()),
                ('stair', models.CharField(max_length=200)),
                ('karkas', models.CharField(max_length=200)),
                ('material', models.CharField(max_length=200)),
                ('rail', models.CharField(max_length=200)),
                ('rail_material', models.CharField(max_length=200)),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('long', models.IntegerField()),
                ('height_step', models.IntegerField()),
                ('obrobka', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('archive', models.BooleanField(default=False)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accclients.client')),
            ],
        ),
    ]
