# Generated by Django 3.1.7 on 2021-05-03 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_orderclient_details'),
        ('conorders', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderClientDetails',
        ),
    ]
